name: rl2018
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.0.0
  - numpy=1.15.2
  - python=3.6.6
  - scipy=1.1.0
  - tqdm=4.26.0
  - pip:
    - gym==0.10.8
    - torch==0.4.1